# Project: test5
# Makefile created by Dev-C++ 5.4.0

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = test5.o $(RES)
LINKOBJ  = test5.o $(RES)
LIBS     = -L"D:/developer_tool/c_toos/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -g3
INCS     = -I"D:/developer_tool/c_toos/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"D:/developer_tool/c_toos/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/include"
BIN      = test5.exe
CXXFLAGS = $(CXXINCS)  -g3
CFLAGS   = $(INCS)  -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

test5.o: test5.c
	$(CC) -c test5.c -o test5.o $(CFLAGS)
